### ISSUE TITLE
Add `random_get()` to the ABI

### ISSUE THREAD

**Issue by mandarjog** [proxy-wasm/spec#12]
A high quality random number is needed for many reasons inside a Wasm module.

[wasi_ephemeral_random.get](https://github.com/WebAssembly/WASI/blob/master/phases/ephemeral/witx/wasi_ephemeral_random.witx) defines such an API. proxy_wasm should use or define a compatible API.

**Comment by mandarjog** [comment]
@PiotrSikora

**Comment by mathetake** [comment]
@mandarjog it's now supported in cpp-host https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/68, and it's upstreamed to Envoy's master branch https://github.com/envoyproxy/envoy/pull/13606Envoy

**Comment by sonhal** [comment]
How can this be called from Rust? Cannot find a mention of it in the Rust SDK

**Comment by PiotrSikora** [comment]
> How can this be called from Rust? Cannot find a mention of it in the Rust SDK

See answer in [the other issue you've opened](https://github.com/proxy-wasm/proxy-wasm-rust-sdk/issues/97) in the Rust SDK.
