### ISSUE TITLE
Reading host's env variables from Wasm VMs

### ISSUE THREAD

**Issue by mathetake** [proxy-wasm/spec#19]
Actually, there's a need for reading envs from Plugins as you can see issues below:

- https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/issues/32
- https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/102

We should have a consensus on how to deal with it, like, 
- having a restriction system to limit which variable can be read from a particular plugin
- just leaving this to the host implementation

this is somewhat related to #17 since this would be implemented as WASI's `environ_get`.

**Comment by xuecanlong** [comment]
and do you have plan to support in https://github.com/proxy-wasm/proxy-wasm-rust-sdk ?

**Comment by mathetake** [comment]
@xuecanlong  
once it's specified in ABI, yeah this would be added to Rust SDK for sure. But we haven't reached any consensus yet. So please stay tuned for the ABI update.

**Comment by xuecanlong** [comment]
@mathetake 
Thanks, I really need it. 
Do we have another way to get `POD_NAMESPACE` and POD DEPLOYMENT NAME?

**Comment by PiotrSikora** [comment]
Note that there is really nothing for the Proxy-Wasm spec to define here (well, other than saying that it's allowed, see: #17), since reading environment variables is already defined in the WASI spec.

This actually already works in the Rust SDK (if you compile it for the `wasm32-wasi` target), but we don't export any variables in Envoy, so the list is empty.

@mathetake if you want to add a key-value map of the variables to export from Envoy, feel free to do it. But this has to be an explicit map (possibly with pass-through for configured values) and not a complete pass-through to the host variables.

**Comment by mathetake** [comment]
> @mathetake if you want to add a key-value map of the variables to export from Envoy, feel free to do it. But this has to be an explicit map (possibly with pass-through for configured values) and not a complete pass-through to the host variables.

OK, will do. Thanks for clarification here!

**Comment by mathetake** [comment]
Created the issue in Envoy side: https://github.com/envoyproxy/envoy/issues/14958. Please refer there for those who are interested in this feature.

**Comment by linzg2002** [comment]
@mathetake I am very interested on this reading host env feature. So I just reviewed all issues and PR around this topic. But still cannot very clear about how to use it in real case. Could you give some tips? Such as how to config it in envoy.yaml and how to write the code in the wasm filter in C++?
I actually had tried like this:
in istio envoyfilter.yaml
```
config:
  root_id: my_root_id
  vm_config:
    code:
      local:
        filename: /var/local/lib/wasm-filters/example-filter.wasm
    runtime: envoy.wasm.runtime.v8
    vm_id: "my_vm_id"
    environment_variables: ["HOME"]
```
in my wasm-filter.cc
```
    this->theHome = std::getenv("HOME");
```
Unluckily,  I got nothing output. So anywrong I did on this? Bwt, is the function support by istio-envoy? and which should the istio version to be at least? Looking forward for your help, thanks in advance.

**Comment by capitanFlint129** [comment]
@linzg2002, it seems to be used like this:
```
environment_variables:
  host_env_keys: ["HOME"]
```
