### ISSUE TITLE
Contribute the host implementation of Golang

### ISSUE THREAD

**Issue by antJack** [proxy-wasm/spec#21]
Recently I implemented the hose side of proxy wasm abi spec in Golang

The project was originally used for MOSN, another data plane for service mesh(kind of like Envoy). Lately, I realized that it can be contributed to the proxy-wasm project.

Currently, the project only implements the 0.1.0 version of abi spec, and the 0.2.x will be supported as soon as possible.

The project also provides a simple example, demonstrating how to use the proxy-wasm host in an HTTP server.

project link:  https://github.com/mosn/proxy-wasm-go-host

I wonder if there are any license requirements or others?

**Comment by PiotrSikora** [comment]
This looks really good, amazing work! Thanks for making it available outside of MOSN - someone asked me about integrating Proxy-Wasm into their in-house Go proxy, and this will be extremelly helpful to them.

What exactly do you mean by contributing? Do you want to move your project to [github.com/proxy-wasm](https://github.com/proxy-wasm) and/or re-assign the copyright? Or did you have something else in mind? Feel free to reach out to me over email (piotrsikora@google.com).

**Comment by antJack** [comment]
Thanks for replying.

The word ‘contribute’ may be somewhat misleading, since the proxy-wasm-go-host project has already belonged to the *group* mosn.io, though I’m trying my best to make it out of the proxy project *MOSN* so that it can be running on other go programs. 

The open-source license we used is Apache2.0, anyone is free to reproduce and distribute our code. And we also welcome any issues and code contributions from the community. 

From my own perspective, I appreciate the efforts of making an impl-agnostic ABI for the proxy scenarios. And I’m willing to pay some effort into the further development of the proxy-wasm project. (eg. completing 0.2.x for go-host, popularizing the proxy-wasm project, engaging in the discussion of the abi spec, etc.)

**Comment by PiotrSikora** [comment]
Yes, I was a little confused by what exactly did you mean by "contribute" and your question about licensing requirements, thanks for clarifying! Keeping proxy-wasm-go-host within `mosn.io` group sounds perfectly fine.

I guess the only thing we need to do now is add MOSN and proxy-wasm-go-host to the list of implementations: #22

**Comment by mathetake** [comment]
resolved by #22
