### ISSUE TITLE
How can a module signal unexpected failure?

### ISSUE THREAD

**Issue by srenatus** [proxy-wasm/spec#23]
Heya. 😃 

I'm playing with the proxy-wasm spec recently, and I've been stumbling upon this: If something goes (terribly) wrong in one of the exported functions of my wasm-module, what can I do about it?

My expectation would be some sort of host function to be imported by the wasm module, say `proxy_abort`, which would be called in those abysmal circumstances.

I may very well just be missing something obvious.... 🤔

**Comment by PiotrSikora** [comment]
You don't need any special Proxy-Wasm host function to do that, your module needs to call Wasm's `unreachable` instruction, and it will be aborted by the Wasm runtime. How to get there depends on the programming language that you're using, but it's pretty idiomatic (e.g. `abort()` in C/C++, `panic()` in Rust, etc.).

**Comment by srenatus** [comment]
Ah OK. Thanks!
