### ISSUE TITLE
The spec should define semantics and values for proxy_result_t

### ISSUE THREAD

**Issue by jpeach** [proxy-wasm/spec#24]
The spec mentions that `proxy_result_t` can express either a success or error status, but does not define how it does that. Looking at the implementation (`enum class WasmResult`), it seems that 0 is success and there is a set of well-defined non-zero error codes. The spec ought to document all these as part.

**Comment by jpeach** [comment]
Looks like this is mostly addressed in https://github.com/proxy-wasm/spec/pull/1.

**Comment by PiotrSikora** [comment]
The vNEXT is unfortunately still a work-in-progress, and not what Envoy and the existing SDKs are implementing, although I'm actively working on fixing that.

Why are you looking at it? Are you implementing either host or another SDK?

**Comment by jpeach** [comment]
> Why are you looking at it? Are you implementing either host or another SDK?

I was reading the spec to get a sense of the underlying concepts and model for writing extensions.

**Comment by mathetake** [comment]
I believe this will be resolved by our project overhaul. Please refer to https://github.com/proxy-wasm/spec/pull/39#issuecomment-1577876577 for the context. Thanks!
