### ISSUE TITLE
Document relationship to WASI

### ISSUE THREAD

**Issue by dippynark** [proxy-wasm/spec#3]
This may be somewhere already that I can't find, but I think it'd be useful to document the relationship of proxy-wasm to WASI as it feels like they have the same goal just in different host environments: https://stackoverflow.com/questions/60969344/what-is-the-relationship-between-wasi-and-proxy-wasm

Are the ABI specs completely different or is there some interoperability (potentially in the future).

**Comment by mathetake** [comment]
Proxy-Wasm is irrelevant to WASI (at least as of preview1), and this spec repository is only about these Proxy specific functions, etc. How WASI will be exposed to the Wasm binary is implementor-speicifc, so I will close this issue. Thanks!

**Comment by PiotrSikora** [comment]
> Proxy-Wasm is irrelevant to WASI (at least as of preview1), and this spec repository is only about these Proxy specific functions, etc. How WASI will be exposed to the Wasm binary is implementor-speicifc, so I will close this issue. Thanks!

This is not true, and we rely on select WASI hostcalls in Proxy-Wasm and the relationship with WASI and future plans regarding it should be documented.
