### ISSUE TITLE
Inconsistency between the spec and implementation. 

### ISSUE THREAD

**Issue by butterunderflow** [proxy-wasm/spec#36]
Hello, I'm a newcomer to proxy-wasm.

It seems there has been some inconsistency between the spec and implementation.
For example, the host interface `proxy_get_map_value` is not used in [Go SDK](https://github.com/tetratelabs/proxy-wasm-go-sdk) nor [Rust SDK](https://github.com/proxy-wasm/proxy-wasm-rust-sdk), they use  `proxy_get_header_map_value` instead. [For example](https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/fcfdccc0150019ff006cc5ff3c932dbe2b5ec080/proxywasm/internal/abi_hostcalls.go#L44). 

Is this intentional or is it a choice of implementations?

**Comment by codefromthecrypt** [comment]
ran into another one today: proxy_send_http_response here, but proxy_send_local_response in the impls. For example, https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/d32cb05cb666216db5e1a383c1ffa2c1aeec19bb/include/proxy-wasm/wasm_api_impl.h#L98

**Comment by mathetake** [comment]
I am closing this issue, but please refer to https://github.com/proxy-wasm/spec/pull/39#issuecomment-1577876577 for the context!
