### ISSUE TITLE
where is the spec?

### ISSUE THREAD

**Issue by bhakta0007** [proxy-wasm/spec#44]
I can't find the spec in the repository. I see that commit 86719f51b29cc1fcdf2d07ae80a6cc7bae0bc99d removed what looked like the spec .. 

Am I missing something?

This document is the closest I have seen that describes the interface methods https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/master/docs/wasm_filter.md

PS: I can refer to the specific implementation document but I am looking for the generic spec here.

**Comment by shukitchan** [comment]
You can check out here for now - https://github.com/proxy-wasm/spec/pull/42
