### ISSUE TITLE
Spec documentation for v0.1.0?

### ISSUE THREAD

**Issue by jonfriesen** [proxy-wasm/spec#46]
Hello,

I know that documentation has been a bit fleeting early on in the ABI spec. I'm curious if there is anything related to v0.1.0 of the ABI spec around? I haven't found anything yet. 

Thanks!

**Comment by PiotrSikora** [comment]
There were minimal differences between v0.1.0, v0.2.0 and v0.2.1. You can find the latter in #42.

I'll add documentation for the other two once #42 is merged, to avoid making changes in 3 versions during the review.
