### ISSUE TITLE
Support Golang SDK

### ISSUE THREAD

**Issue by haorenfsa** [proxy-wasm/spec#6]
Is there any plan to support golang SDK recently? My team are planning to use golang to develop envoy extensions. We're considering implementing a proxy-wasm golang SDK by given spec if there's no recent plan to do so.

**Comment by mathetake** [comment]
https://github.com/mathetake/proxy-wasm-go here's go sdk powered by TinyGo compiler. 

If you have any question, please let me konw. Thanks

**Comment by haorenfsa** [comment]
> https://github.com/mathetake/proxy-wasm-go here's go sdk powered by TinyGo compiler.
> 
> If you have any question, please let me konw. Thanks

Thx for sharing
