### ISSUE TITLE
How to configurable maximum CPU time？

### ISSUE THREAD

**Issue by taoyuanyuan** [proxy-wasm/spec#8]
have any doc about limit CPU time？ thx
https://github.com/proxy-wasm/spec/blob/master/docs/WebAssembly-in-Envoy.md
```
Configurable resource constraints
Each configured Proxy-Wasm extension can set resource constraints (maximum memory each VM can allocate, and maximum CPU time it can consume during each invocation) in order to limit resource usage.
```

**Comment by mathetake** [comment]
I believe this is an implementor-specific issue (ATS, Envoy, Nginx), not the spec. So I am closing. Thanks!
